
services:
  gateway-service:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
      #network: host  # uncomment if you wanna use host networking.
    container_name: gateway-service
    ports:
      - "8081:8081"
    networks:
      - social_service_dev_network

networks:
  social_service_dev_network:
    external: true