version: '3.8'


services:
## eureka server
#  eureka_server:
#        container_name: eureka_server
#        build:
#          context: ./services/discovery-service
#          dockerfile: ./docker/dev/Dockerfile.dev
#        ports:
#        - "8761:8761"
#        networks:
#        - social_service_dev_network
#
### api gateway
#  api_gateway:
#        container_name: api_gateway
#        build:
#          context: ./services/api-gateway
#          dockerfile: ./docker/dev/Dockerfile.dev
#        ports:
#        - "8080:8080"
#        networks:
#        - social_service_dev_network
#        depends_on:
#          - main_service_app

  main_service_db:
    container_name: social_service_dev_db
    build:
      context: ./services/main-service
      dockerfile: ./docker/dev/Dockerfile.dev.psql
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - social_service_dev_db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
        - social_service_dev_network

  main_service_app:
    container_name: dev_api
    build:
        context: ./services/main-service
        dockerfile: ./docker/dev/Dockerfile.dev

    env_file:
      - ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main_service_db:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRE_IN_MS: ${JWT_EXPIRE_IN_MS}
      JWT_SINGING_KEY: ${JWT_SINGING_KEY}
      OPEN_API_DEV_URL: ${OPEN_API_DEV_URL}
      OPEN_API_PRODUCTION_URL: ${OPEN_API_PRODUCTION_URL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      FILE_UPLOAD_DIR: /uploads
      MAIL_SERVICE_HOST: 'smtp.gmail.com'
      MAIL_SERVICE_PORT: 587
      MAIL_SERVICE_USERNAME: your_email@service.domain
      MAIL_SERVICE_PASSWORD: 'google apps password'
      SPRING_PROFILES_ACTIVE: dev

    ports:
      - "8083:8083"

    depends_on:
        - main_service_db
    volumes:
        - upload_dir:/uploads
    networks:
          - social_service_dev_network

## chat service

## notification service

## search service

volumes:
    social_service_dev_db:
    upload_dir:

networks:
    social_service_dev_network:
      driver: bridge

