spring:
  config:
    import: optional:file:.env[.properties]
  # ======================= App =======================
  application:
    name: real-estate-server
  # ======================= Database =======================
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_PROD_NAME}
    username: ${DATABASE_PROD_USERNAME}
    password: ${DATABASE_PROD_PASSWORD}
    #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
  # ======================= Hibernate =======================
  # Hibernate ddl auto (create, create-drop, validate, update)
  #spring.jpa.hibernate.ddl-auto=update
  #spring.jpa.properties.hibernate.format_sql=true
  #spring.jpa.show-sql=true
  jpa:
    #- avoid lazy initialization error.
    open-in-view: false
  # ======================= File Limit =======================
  servlet:
    multipart:
      # Maximum file size
      max-file-size: 5MB
      # Maximum request size
      max-request-size: 6MB
  #===================== Mail Sender ==========================
  mail:
    host: ${MAIL_SERVICE_HOST}
    port: ${MAIL_SERVICE_PORT}
    username: ${MAIL_SERVICE_USERNAME}
    password: ${MAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000

server:
  port: ${PRODUCTION_PORT}

# ======================= JWT =======================
app:
  jwtSecret: ${JWT_SECRET_KEY}
  jwtExpirationMs: ${JWT_EXPIRE_IN_MS}

token:
  signing:
    key: ${JWT_SINGING_KEY}

# ======================= Swagger =======================
osama_mh:
  openapi:
    dev-url: ${OPEN_API_DEV_URL}
    prod-url: ${OPEN_API_PRODUCTION_URL}
    localhost-url: http://localhost:${PORT:8081}

# ======================= encryption =======================
encryption:
  key: ${ENCRYPTION_KEY}

# ======================= File Upload =======================
# Default file upload directory for local development
file:
  upload-dir: src/main/resources/static/uploads/

#elk stack
logstash:
  host: localhost
  port: 5000
# Enable Spring property resolution in Logback
#logging.config=classpath:logback-spring.xml
