
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=123456
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Limit Elasticsearch JVM memory
      - xpack.security.enabled=false  # Disable security for dev mode
      - xpack.security.http.ssl.enabled=false
      - bootstrap.memory_lock=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - social_service_dev_network
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          cpus: "1.0"   # Limit to 1 CPU
          memory: "2GB"  # Limit to 2GB RAM
        reservations:
          cpus: "0.5"   # Reserve 0.5 CPU
          memory: "1GB"  # Reserve 1GB RAM

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"  # Beats input
      - "5000:5000"  # TCP input
      - "9600:9600"  # Monitoring
    networks:
      - social_service_dev_network
    deploy:
      resources:
        limits:
          cpus: "0.7"  # Limit Logstash to 0.7 CPU
          memory: "1GB"  # Limit to 1GB RAM
        reservations:
          cpus: "0.3"  # Reserve 0.3 CPU
          memory: "512MB"  # Reserve 512MB RAM

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false  # Disable security for dev mode
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - social_service_dev_network
    volumes:
      - kibana_data:/usr/share/kibana/data
    deploy:
      resources:
        limits:
          cpus: "0.5"  # Limit Kibana to 0.5 CPU
          memory: "750MB"  # Limit to 750MB RAM
        reservations:
          cpus: "0.3"  # Reserve 0.3 CPU
          memory: "500MB"  # Reserve 500MB RAM

networks:
  social_service_dev_network:
    external: true

volumes:
  elasticsearch_data:
  kibana_data:
