package com.app.server.enums;

public enum NotificationType {
    REQUEST_FRIENDSHIP,
    ACCEPT_FRIENDSHIP,

    COMMENTED_YOUR_POST,

    REACTED_TO_YOUR_POST,
    REACTED_TO_YOUR_COMMENT,
    REPLIED_TO_YOUR_COMMENT,

    POSTED_NEW_CONTENT
}
