# Use the official Maven image to create a build artifact
FROM maven:3.8.4-openjdk-17-slim AS build

# Set the working directory
WORKDIR /app

# Copy the pom.xml and download dependencies
COPY ../../pom.xml .
RUN mvn dependency:go-offline

# Copy the source code and build the application
COPY ../../src ./src
RUN mvn clean package -DskipTests

# Use OpenJDK for running the application
FROM openjdk:17-slim

# Set environment variables
# Set environment variables
ENV APP_HOME=/app
ENV UPLOAD_DIR=/uploads

WORKDIR $APP_HOME
# Create the upload directory
RUN mkdir -p $UPLOAD_DIR

# Copy the JAR file from the build stage
COPY --from=build /app/target/*.jar app.jar

# Set the active profile to docker
ENV SPRING_PROFILES_ACTIVE=docker

# Expose the application's port
EXPOSE 8083

# Add a health check
#HEALTHCHECK --interval=30s --timeout=10s --start-period=10s \
#  CMD curl --fail http://localhost:8081/actuator/health || exit 1

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
