version: '3.8'

services:
  db:
    container_name: social_service_dev_db
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile.dev.psql
    env_file:
      - ../../services/mainService/.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
        - social_service_dev_network

  app:
    container_name: dev_api
    build:
        context: ../../
        dockerfile: docker/dev/Dockerfile.dev

    env_file:
      - ../../services/mainService/.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DATABASE_NAME}
      SPRING_DATASOURCE_USERNAME: ${DATABASE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRE_IN_MS: ${JWT_EXPIRE_IN_MS}
      JWT_SINGING_KEY: ${JWT_SINGING_KEY}
      OPEN_API_DEV_URL: ${OPEN_API_DEV_URL}
      OPEN_API_PRODUCTION_URL: ${OPEN_API_PRODUCTION_URL}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      FILE_UPLOAD_DIR: /uploads
      MAIL_SERVICE_HOST: 'smtp.gmail.com'
      MAIL_SERVICE_PORT: 587
      MAIL_SERVICE_USERNAME: your_email@service.domain
      MAIL_SERVICE_PASSWORD: 'google apps password'
      SPRING_PROFILES_ACTIVE: dev

    ports:
      - "8081:8081"
    depends_on:
      - db
    volumes:
      - upload_dir:/uploads
    networks:
        - social_service_dev_network

volumes:
  db_data:
  upload_dir:

networks:
  social_service_dev_network:
    driver: bridge
