version: '3.8'

services:
  discovery-service:
    build:
      context: .
      dockerfile: Dockerfile
      network: host  # ✅ FIX
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - social_service_dev_network

networks:
  social_service_dev_network:
    external: true