
services:
  discovery-service:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
      #network: host  # ✅ FIX
    container_name: eureka-server
    ports:
      - "8085:8085"
    networks:
      - social_service_dev_network

networks:
  social_service_dev_network:
    external: true